version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    command: >
      /usr/local/bin/etcd
      --name my-etcd
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --listen-peer-urls http://0.0.0.0:2380
      --initial-cluster my-etcd=http://0.0.0.0:2380
    ports:
      - "2379:2379"
    networks:
      - flyserver

  etcd-keeper:
    image: evildecay/etcdkeeper:latest
    container_name: etcd-keeper
    ports:
      - "61002:8080"
    environment:
      - ETCD_SERVERS http://etcd:2379
    networks:
      - flyserver

  project:
    image: golang:1.19
    container_name: project
    build:
        context: .
        dockerfile: Dockerfile
    working_dir: /go/src/project
    volumes:
      - .:/go/src/project
    ports:
      - "61001:8080"
    networks:
      - flyserver
    tty: true

networks:
  flyserver:
    driver: bridge
